// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEHaQTb9ZIxl-kCt4UKScb3S3e9M79sRE',
    appId: '1:645381910519:web:5729c63d2c213e6c7348f2',
    messagingSenderId: '645381910519',
    projectId: 'the-lock-in-factory',
    authDomain: 'the-lock-in-factory.firebaseapp.com',
    storageBucket: 'the-lock-in-factory.firebasestorage.app',
    measurementId: 'G-FK44EHFE9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyCSGCfvDIGfmgO4lu499N-XUVDNjrFcQ',
    appId: '1:645381910519:android:f612578ef27a92d87348f2',
    messagingSenderId: '645381910519',
    projectId: 'the-lock-in-factory',
    storageBucket: 'the-lock-in-factory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPsvsX_rY_R5ya2PHRxOwMZzGaua2W9Ek',
    appId: '1:645381910519:ios:070e02cacf0272487348f2',
    messagingSenderId: '645381910519',
    projectId: 'the-lock-in-factory',
    storageBucket: 'the-lock-in-factory.firebasestorage.app',
    iosBundleId: 'com.example.theLockInFactory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPsvsX_rY_R5ya2PHRxOwMZzGaua2W9Ek',
    appId: '1:645381910519:ios:070e02cacf0272487348f2',
    messagingSenderId: '645381910519',
    projectId: 'the-lock-in-factory',
    storageBucket: 'the-lock-in-factory.firebasestorage.app',
    iosBundleId: 'com.example.theLockInFactory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEHaQTb9ZIxl-kCt4UKScb3S3e9M79sRE',
    appId: '1:645381910519:web:9f143c1c56d6b3b97348f2',
    messagingSenderId: '645381910519',
    projectId: 'the-lock-in-factory',
    authDomain: 'the-lock-in-factory.firebaseapp.com',
    storageBucket: 'the-lock-in-factory.firebasestorage.app',
    measurementId: 'G-6XMXFDZJ3Q',
  );
}
